# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eccc9ea8a607296e9245c11df039566edeeca3854efcb215b6b487ba99b0586594e5483863388a8127006de909671c09293c9db0615431e25aa681fbfea1a681

test:
  secret_key_base: 8c44a6f71d480e1f8f516978f2b5e824c72a623416dcaf144a71deea21180f1ccb5534a45735cbab02591cff30c983fdedaa0d3dce44f7b4fbd65944e9fd38ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
